import re
import os
from datetime import datetime
from fpdf import FPDF
from app.models.schemas import ExtractedIntel

def generate_scam_report(session_id: str, intel: ExtractedIntel, persona_name: str) -> str:
    """
    Generates a PDF report for the National Cyber Crime Reporting Portal.
    Returns the path to the generated PDF.
    """
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Cyber Crime Incident Report", ln=True, align="C")
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
    pdf.ln(10)

    # Incident Details
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "1. Incident Overview", ln=True)
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 10, f"Session ID: {session_id}\nAssigned Persona: {persona_name}\nStatus: Intelligence Gathered")
    pdf.ln(5)

    # Extracted Intelligence
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "2. Extracted Intelligence (Forensics)", ln=True)
    pdf.set_font("Arial", "", 10)
    
    if intel.upi_ids:
        pdf.set_font("Arial", "B", 10)
        pdf.cell(0, 8, "UPI IDs Identified:", ln=True)
        pdf.set_font("Arial", "", 10)
        for upi in intel.upi_ids:
            pdf.cell(0, 8, f"- {upi}", ln=True)
    
    if intel.bank_details:
        pdf.set_font("Arial", "B", 10)
        pdf.cell(0, 8, "Bank Account Details:", ln=True)
        pdf.set_font("Arial", "", 10)
        for bank in intel.bank_details:
            pdf.cell(0, 8, f"- {bank}", ln=True)

    if intel.phishing_links:
        pdf.set_font("Arial", "B", 10)
        pdf.cell(0, 8, "Suspicious/Phishing Links:", ln=True)
        pdf.set_font("Arial", "", 10)
        for link in intel.phishing_links:
            pdf.cell(0, 8, f"- {link}", ln=True)
            
    if not any([intel.upi_ids, intel.bank_details, intel.phishing_links]):
        pdf.cell(0, 8, "No financial or malicious markers identified in this session yet.", ln=True)

    pdf.ln(10)

    # Footer/Legal Disclaimer
    pdf.set_font("Arial", "I", 8)
    pdf.multi_cell(0, 5, "This report is generated by the Agentic Honeypot System for submission to the National Cyber Crime Reporting Portal (cybercrime.gov.in). The data contained herein is for investigative purposes only.")

    # Save PDF
    reports_dir = os.path.join(os.getcwd(), "reports")
    if not os.path.exists(reports_dir):
        os.makedirs(reports_dir)
    
    filename = f"report_{session_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = os.path.join(reports_dir, filename)
    pdf.output(file_path)
    
    return filename

def extract_intelligence(text: str) -> ExtractedIntel:
    intel = ExtractedIntel()
    
    # Normalize text for better extraction (handle some obfuscation)
    # 1. Remove common separators between digits in what looks like a bank account
    normalized_text = text.lower()
    
    # Regex for UPI IDs
    upi_pattern = r'[a-zA-Z0-9.\-_]{2,256}@[a-zA-Z]{2,64}'
    intel.upi_ids = list(set(re.findall(upi_pattern, text)))

    # Regex for URLs
    url_pattern = r'https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+'
    intel.phishing_links = list(set(re.findall(url_pattern, text)))

    # Heuristic for Bank Accounts (9-18 digits)
    # Try finding digits even with spaces or dashes between them
    digit_sequences = re.findall(r'(?:\d[\s-]*){9,18}\d', text)
    cleaned_digits = [re.sub(r'[\s-]', '', d) for d in digit_sequences]
    intel.bank_details = list(set(cleaned_digits))

    return intel